## Cleaning notebook

In [28]:
import pandas as pd
df = pd.read_csv("../data/raw/JPM_balance_sheet.csv", index_col=0)
df.head()

,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Treasury Shares Number,1.307313e+09,1.228275e+09,1.170676e+09,1.160785e+09
Preferred Shares Number,3.918500e+08,3.918500e+08,3.918500e+08,3.918500e+08
Ordinary Shares Number,2.797620e+09,2.876659e+09,2.934258e+09,2.944149e+09
Share Issued,4.104934e+09,4.104934e+09,4.104934e+09,4.104934e+09
Total Debt,4.543110e+11,4.365370e+11,3.398920e+11,3.545990e+11

In [29]:
df.index

Index(['Treasury Shares Number', 'Preferred Shares Number',
       'Ordinary Shares Number', 'Share Issued', 'Total Debt',
       'Tangible Book Value', 'Invested Capital', 'Net Tangible Assets',
       'Common Stock Equity', 'Preferred Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Treasury Stock', 'Retained Earnings',
       'Additional Paid In Capital', 'Capital Stock', 'Common Stock',
       'Preferred Stock', 'Total Liabilities Net Minority Interest',
       'Long Term Debt And Capital Lease Obligation', 'Long Term Debt',
       'Current Debt And Capital Lease Obligation', 'Current Debt',
       'Other Current Borrowings', 'Payables And Accrued Expenses', 'Payables',
       'Other Payable', 'Accounts Payable', 'Total Assets',
       'Investments And Advances', 'Held To Maturity Securities',
       'Trading Securities', 'Goodwill And Other Intangible Assets',
       'Other Intangible Assets', 'Goodwill', 'Net PPE', 'Gross PPE',
       'Other Properties', 'Properties', 'Receivables', 'Accounts Receivable',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Financial', 'Cash Cash Equivalents And Federal Funds Sold'],
      dtype='object')

In [30]:
df=df.T

In [31]:
# Deal with nulls
df.isna
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

In [32]:
# Scale values
df = (df / 1_000_000).round(2)
df.head()

,Treasury Shares Number,Preferred Shares Number,Ordinary Shares Number,Share Issued,Total Debt,Tangible Book Value,Invested Capital,Net Tangible Assets,Common Stock Equity,Preferred Stock Equity,...,Net PPE,Gross PPE,Other Properties,Properties,Receivables,Accounts Receivable,Other Short Term Investments,Cash And Cash Equivalents,Cash Financial,Cash Cash Equivalents And Federal Funds Sold
2024-12-31,1307.31,391.85,2797.62,4104.93,454311.0,260148.0,779019.0,280198.0,324708.0,20050.0,...,32223.0,32223.0,15349.0,16874.0,101223.0,101223.0,396690.0,469317.0,23372.0,764318.0
2023-12-31,1228.28,391.85,2876.66,4104.93,436537.0,236093.0,737011.0,263497.0,300474.0,27404.0,...,30157.0,30157.0,15295.0,14862.0,107363.0,107363.0,192485.0,624151.0,29066.0,900303.0
2022-12-31,1170.68,391.85,2934.26,4104.93,339892.0,204069.0,604820.0,231473.0,264928.0,27404.0,...,27734.0,27734.0,14248.0,13486.0,125189.0,125189.0,196699.0,567234.0,27697.0,882826.0
2021-12-31,1160.78,391.85,2944.15,4104.93,354599.0,202598.0,613888.0,237436.0,259289.0,34838.0,...,27070.0,0.0,0.0,0.0,102570.0,102570.0,290257.0,740834.0,26438.0,1002532.0

In [33]:
df.to_csv("../data/processed/JPM_balance_sheet_clean.csv")

In [34]:
df = pd.read_csv("../data/raw/WFC_balance_sheet.csv", index_col=0)
df.head()

,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Treasury Shares Number,2.192868e+09,1.882949e+09,1.648007e+09,1.596010e+09
Preferred Shares Number,2.509645e+08,2.845645e+08,3.535645e+08,3.535645e+08
Ordinary Shares Number,3.288944e+09,3.598863e+09,3.833804e+09,3.885801e+09
Share Issued,5.481811e+09,5.481811e+09,5.481811e+09,5.481811e+09
Net Debt,NaN,NaN,3.621300e+10,NaN

In [35]:
#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
(df / 1_000_000).round(2)

# Store processed file
df.to_csv("../data/processed/WFC_balance_sheet_clean.csv")

In [38]:
# Read file
df=pd.read_csv("../data/raw/C_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
(df / 1_000_000).round(2)

# Store processed file
df.to_csv("../data/processed/C_balance_sheet_clean.csv")

In [40]:
# Read file
df=pd.read_csv("../data/raw/GS_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=(df / 1_000_000).round(2)

# Store processed file
df.to_csv("../data/processed/GS_balance_sheet_clean.csv")

In [43]:
# Read file
df=pd.read_csv("../data/raw/BAC_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=(df / 1_000_000).round(2)

# Store processed file
df.to_csv("../data/processed/BAC_balance_sheet_clean.csv")

**Clean the income statements**

In [49]:
df=pd.read_csv("../data/raw/JPM_income_statement.csv",index_col=0)
df=df.T
df=df.dropna(axis=1, how='all')
df=df.fillna(0)
df=(df/1_000_000).round(2)
df.head()
df.to_csv('../data/processed/JPM_income_statement_clean.csv')

**Single code for all Cleaned Income statements updates**

In [ ]:
tickers = ["JPM", "BAC", "GS", "WFC", "C"]

for ticker in tickers:
    # Read raw file
    df = pd.read_csv(f"../data/raw/{ticker}_income_statement.csv",index_col=0)

    # Cleaning steps
    df = df.T
    df = df.dropna(axis=1, how="all")
    df = df.fillna(0)
    df = (df / 1_000_000).round(2)

    # Save cleaned file
    df.to_csv(f"../data/processed/{ticker}_income_statement_clean.csv")