## Cleaning notebook

In [128]:
import pandas as pd
df = pd.read_csv("../data/raw/JPM_balance_sheet.csv", index_col=0)
df.head()

                2023-12-31    2022-12-31    2021-12-31
2024-12-31
1.307313e+09  1.228275e+09  1.170676e+09  1.160785e+09
3.918500e+08  3.918500e+08  3.918500e+08  3.918500e+08
2.797620e+09  2.876659e+09  2.934258e+09  2.944149e+09
4.104934e+09  4.104934e+09  4.104934e+09  4.104934e+09
4.543110e+11  4.365370e+11  3.398920e+11  3.545990e+11

In [ ]:
df=df.T

2024-12-31,6.168460e+08,9.199800e+07,3.106537e+08,9.274997e+08,1.584010e+11,3.425550e+11,1.020430e+11,4.492360e+11,1.152960e+11,2.062000e+09,...,9.991000e+09,-1.364000e+10,2.363100e+10,2.363100e+10,1.512130e+11,1.749600e+10,1.337170e+11,3.646000e+10,1.820920e+11,3.621540e+11
2023-12-31,599.518678,91.998,323.376354,922.895032,89439.0,333248.0,98609.0,436718.0,109812.0,2232.0,...,13415.0,-13640.0,27055.0,27055.0,148577.0,16082.0,132495.0,33173.0,241577.0,465382.0
2022-12-31,582.896393,159.998,334.918639,917.815032,80220.0,324199.0,98103.0,428531.0,108806.0,2154.0,...,19246.0,-12190.0,31436.0,31436.0,147027.0,11579.0,135448.0,13180.0,241825.0,466942.0
2021-12-31,572.857062,159.998,333.573254,906.430316,58555.0,321879.0,94520.0,418814.0,105223.0,2288.0,...,20386.0,-10180.0,30566.0,30566.0,170192.0,9519.0,160673.0,25.0,261036.0,466739.0

In [144]:
# Deal with nulls
df.isna
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

In [145]:
# Scale values
df = df / 1_000_000
df.head()

2024-12-31,6.168460e+08,9.199800e+07,3.106537e+08,9.274997e+08,1.584010e+11,3.425550e+11,1.020430e+11,4.492360e+11,1.152960e+11,2.062000e+09,...,9.991000e+09,-1.364000e+10,2.363100e+10,2.363100e+10,1.512130e+11,1.749600e+10,1.337170e+11,3.646000e+10,1.820920e+11,3.621540e+11
2023-12-31,0.000600,0.000092,0.000323,0.000923,0.089439,0.333248,0.098609,0.436718,0.109812,0.002232,...,0.013415,-0.01364,0.027055,0.027055,0.148577,0.016082,0.132495,0.033173,0.241577,0.465382
2022-12-31,0.000583,0.000160,0.000335,0.000918,0.080220,0.324199,0.098103,0.428531,0.108806,0.002154,...,0.019246,-0.01219,0.031436,0.031436,0.147027,0.011579,0.135448,0.013180,0.241825,0.466942
2021-12-31,0.000573,0.000160,0.000334,0.000906,0.058555,0.321879,0.094520,0.418814,0.105223,0.002288,...,0.020386,-0.01018,0.030566,0.030566,0.170192,0.009519,0.160673,0.000025,0.261036,0.466739

In [132]:
df.to_csv("../data/processed/JPM_balance_sheet_clean.csv")

In [133]:
df = pd.read_csv("../data/raw/WFC_balance_sheet.csv", index_col=0)
df.head()

                2023-12-31    2022-12-31    2021-12-31
2024-12-31
2.192868e+09  1.882949e+09  1.648007e+09  1.596010e+09
2.509645e+08  2.845645e+08  3.535645e+08  3.535645e+08
3.288944e+09  3.598863e+09  3.833804e+09  3.885801e+09
5.481811e+09  5.481811e+09  5.481811e+09  5.481811e+09
NaN                    NaN  3.621300e+10           NaN

In [134]:
#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=df/ 1_000_000

# Store processed file
df.to_csv("../data/processed/WFC_balance_sheet_clean.csv")

In [135]:
# Read file
df=pd.read_csv("../data/raw/BAC_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=df/ 1_000_000

# Store processed file
df.to_csv("../data/processed/BAC_balance_sheet_clean.csv")

In [136]:
# Read file
df=pd.read_csv("../data/raw/C_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=df/ 1_000_000

# Store processed file
df.to_csv("../data/processed/C_balance_sheet_clean.csv")

In [137]:
# Read file
df=pd.read_csv("../data/raw/GS_balance_sheet.csv", index_col=0)

#Transpose
df = df.T
df

# Deal with nulls
df.isna()
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

# Scale values
df=df/ 1_000_000

# Store processed file
df.to_csv("../data/processed/GS_balance_sheet_clean.csv")