## Cleaning notebook

In [ ]:
import pandas as pd
df = pd.read_csv("../data/raw/JPM_balance_sheet.csv", index_col=0)
df.head()

                2023-12-31    2022-12-31    2021-12-31
2024-12-31
1.307313e+09  1.228275e+09  1.170676e+09  1.160785e+09
3.918500e+08  3.918500e+08  3.918500e+08  3.918500e+08
2.797620e+09  2.876659e+09  2.934258e+09  2.944149e+09
4.104934e+09  4.104934e+09  4.104934e+09  4.104934e+09
4.543110e+11  4.365370e+11  3.398920e+11  3.545990e+11

In [6]:
#Transpose
df = df.T
df

2024-12-31,1.307313e+09,3.918500e+08,2.797620e+09,4.104934e+09,4.543110e+11,2.601480e+11,7.790190e+11,2.801980e+11,3.247080e+11,2.005000e+10,...,3.222300e+10,3.222300e+10,1.534900e+10,1.687400e+10,1.012230e+11,1.012230e+11,3.966900e+11,4.693170e+11,2.337200e+10,7.643180e+11
2023-12-31,1.228275e+09,391850000.0,2.876659e+09,4.104934e+09,4.365370e+11,2.360930e+11,7.370110e+11,2.634970e+11,3.004740e+11,2.740400e+10,...,3.015700e+10,3.015700e+10,1.529500e+10,1.486200e+10,1.073630e+11,1.073630e+11,1.924850e+11,6.241510e+11,2.906600e+10,9.003030e+11
2022-12-31,1.170676e+09,391850000.0,2.934258e+09,4.104934e+09,3.398920e+11,2.040690e+11,6.048200e+11,2.314730e+11,2.649280e+11,2.740400e+10,...,2.773400e+10,2.773400e+10,1.424800e+10,1.348600e+10,1.251890e+11,1.251890e+11,1.966990e+11,5.672340e+11,2.769700e+10,8.828260e+11
2021-12-31,1.160785e+09,391850000.0,2.944149e+09,4.104934e+09,3.545990e+11,2.025980e+11,6.138880e+11,2.374360e+11,2.592890e+11,3.483800e+10,...,2.707000e+10,NaN,NaN,NaN,1.025700e+11,1.025700e+11,2.902570e+11,7.408340e+11,2.643800e+10,1.002532e+12

In [22]:
# Deal with nulls
df.isna
df = df.dropna(axis=1, how="all")
df = df.fillna(0)

In [25]:
# Scale values
df = df / 1_000_000

In [30]:
df.to_csv("../data/processed/JPM_balance_sheet_clean.csv")